name: Shopping CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git pull
        uses: actions/checkout@v2
      
      - name: PWD
       
        env:
          AWS_EC2_KEY: ${{ secrets.AWS_EC2_PEM  }}
          AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_PUBLIC_IP  }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME  }}
        run: | 
          echo "paso 01"
          pwd
          echo "$AWS_EC2_KEY" > private_key && chmod 600 private_key
          ls
          ssh -o StrictHostKeyChecking=no -i private_key $AWS_EC2_USERNAME@$AWS_EC2_PUBLIC_IP '
            cd /var/www/shopping-backend
            
            sudo git checkout development
            
            sudo git pull origin development
            
            sudo docker-compose down
            
            sudo docker-compose up --build --force-recreate -d
          '