name: Shopping Car CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git pull
        uses: actions/checkout@v2

      - name: PWD

        env:
          AWS_EC2_KEY: ${{ secrets.AWS_EC2_PEM  }}
          AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_PUBLIC_IP  }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME  }}
        run: | 
          pwd
          echo "$AWS_EC2_KEY" > private_key && chmod 600 private_key
          ls
          ssh -o StrictHostKeyChecking=no -i private_key $AWS_EC2_USERNAME@$AWS_EC2_PUBLIC_IP '
            cd /var/www/shopping-backend
            echo "paso 1" 
            sudo git checkout develop
            echo "paso 2" 
            sudo git pull origin develop
            echo "paso 3"
            sudo docker-compose down
            echo "paso 4" 
            sudo docker-compose up --build --force-recreate -d
          '
